application: recycled-app
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon.ico
  static_files: /images/favicon.ico
  upload: /images/favicon.ico
- url: /purgemain
  script: recycled-app.application
  login: admin
- url: /images
  static_dir: images
- url: /.*
  script: recycled-app.application


libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest